# Generated by Django 3.2.3 on 2021-05-18 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_alter_article_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='crudapp.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.TextField(default=1621315794.7281065),
        ),
    ]
