# Generated by Django 3.2.3 on 2021-05-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_auto_20210518_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='modify_at',
        ),
        migrations.AddField(
            model_name='article',
            name='update_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='create_at',
            field=models.TextField(default=1621917967.694106),
        ),
        migrations.AddField(
            model_name='tag',
            name='update_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.TextField(default=1621917967.694106),
        ),
    ]
